### ISSUE TITLE
poky:  error: 'ret' may be used uninitialized in this function

### ISSUE THREAD

**Issue by geissonator** [openbmc/phosphor-power#3]
Latest poky upstream causes the below error. Poky commit is at https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/39002/1 and the jenkins job is currently at https://jenkins.openbmc.org/job/ci-openbmc/1276/distro=ubuntu,label=docker-builder,target=witherspoon/consoleFull
```
| ../git/tools/i2c/i2c.cpp: In member function 'virtual void i2c::I2CDevice::read(uint8_t, uint8_t&, uint8_t*, i2c::I2CInterface::Mode)':
| ../git/tools/i2c/i2c.cpp:220:5: error: 'ret' may be used uninitialized in this function [-Werror=maybe-uninitialized]
|   220 |     if (ret < 0)
|       |     ^~
| ../git/tools/i2c/i2c.cpp: In member function 'virtual void i2c::I2CDevice::write(uint8_t, uint8_t, const uint8_t*, i2c::I2CInterface::Mode)':
| ../git/tools/i2c/i2c.cpp:276:5: error: 'ret' may be used uninitialized in this function [-Werror=maybe-uninitialized]
|   276 |     if (ret < 0)
|       |     ^~
| cc1plus: all warnings being treated as errors
```

FYI @smccarney

**Comment by leiyu-bytedance** [comment]
The code depends on the `switch-case` without `default`, so it assumes the `ret` will always get a value.
There could be a quick fix to initialize the variable `ret` to -1.
I will post a fix.

What concerns me is that this "warning" is not reported in repo-ci, but got caught in the openbmc build.
Possibly poky upstream adds some more strict warning levels in compiler flags that the repo-ci does not use.
In that case, I am not sure if we will see similar errors in other repos.

**Comment by leiyu-bytedance** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/39004
