### ISSUE TITLE
Fix the define IBM_VPD in psu-ng app

### ISSUE THREAD

**Issue by chnguyen-ampere** [openbmc/phosphor-power#5]
Hi,

In the **meson_option.txt**, it set the "**ibm-vpd**" is a false value. So, the **IBM_VPD** will be 0
To verify that can check the config.h file in the corresponding build directory.

**config.h**
![Screen Shot 2021-03-26 at 6 13 57 PM](https://user-images.githubusercontent.com/72901438/112623550-0f05ae80-8e5f-11eb-9c9f-bf839c4c1458.png)

I saw in the **phosphor-power-supply/power_supply.cpp**, we used the "#ifdef IBM_VPD" to check the define IBM_VPD. BUT it's not correct completely. The source code of IBM VPD always runs in both TRUE or FALSE.

I think we should replace the "**#ifdef IBM_VPD**"  by "**#if IBM_VPD**" 

Thanks

**Comment by chnguyen-ampere** [comment]
Hi @bjwyman , please help me review this issue! Thanks!

**Comment by bjwyman** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/41991

**Comment by bjwyman** [comment]
https://github.com/openbmc/phosphor-power/commit/c12c53b985b9ac12c3c83df47371e7c2c70ae21b

**Comment by smccarney** [comment]
This change has been merged.
