### ISSUE TITLE
Project targeting '>=0.57.0' but tried to use feature deprecated since '0.56.0'

### ISSUE THREAD

**Issue by bjwyman** [openbmc/phosphor-power#8]
When doing local CI builds, nothing complaints about meson version and options we are using:

```
WARNING: Project targeting '>=0.57.0' but tried to use feature deprecated since '0.56.0': Dependency.get_pkgconfig_variable. use Dependency.get_variable(pkgconfig : ...) instead
Configuring config.h using configuration
WARNING: Project targeting '>=0.57.0' but tried to use feature deprecated since '0.56.0': meson.source_root. use meson.project_source_root() or meson.global_source_root() instead.
Build targets in project: 22
WARNING: Deprecated features used:
 * 0.56.0: {'meson.source_root', 'Dependency.get_pkgconfig_variable'}
```

**Comment by bjwyman** [comment]
Some meson tidbits in a link from the feeds channel in OpenBMC Discord: http://www.stwcx.xyz/blog/2021/04/18/meson-subprojects.html
Not sure if something related to these warnings is covered there.

**Comment by williamspatrick** [comment]
Some other repos have been cleaning these up as well.  It should be a relatively minor change.  An example commit to use as a pattern is probably this:
    https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/49970

**Comment by matthewfischer** [comment]
Closable - Fixed by this commit - https://github.com/openbmc/phosphor-power/commit/95f6aab2909b45cdb273240da75ced29e5b22f39
